// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHFI8onr8Lroo8qKileF3m7h5JNYZT-Y0',
    appId: '1:262756461806:web:0a3363effb778bcf6117ff',
    messagingSenderId: '262756461806',
    projectId: 'flutter-chat-app-843df',
    authDomain: 'flutter-chat-app-843df.firebaseapp.com',
    storageBucket: 'flutter-chat-app-843df.firebasestorage.app',
    measurementId: 'G-9ZC4TQ1486',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzLa4pBXyOL1LeDcKVJ0vamZHlI4Bv4eE',
    appId: '1:262756461806:android:8ca938ffe0db792e6117ff',
    messagingSenderId: '262756461806',
    projectId: 'flutter-chat-app-843df',
    storageBucket: 'flutter-chat-app-843df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkLu5YQDgJGrm577-SG237lstBDSG0wUU',
    appId: '1:262756461806:ios:a877cc573fa1edb66117ff',
    messagingSenderId: '262756461806',
    projectId: 'flutter-chat-app-843df',
    storageBucket: 'flutter-chat-app-843df.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
